version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: rfid_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - rfid-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro   # (optional) if you serve static files
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: mysql:8.0
    container_name: rfid_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rfid_db
      MYSQL_USER: rfid
      MYSQL_PASSWORD: rfidpass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    # Remove port mapping as it's only needed internally
    ports:
      - "3306:3306"  # Expose MySQL port for external access
    expose:
      - "3306"
    networks:
      - rfid-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prfidpass", "-urfid"]
      interval: 20s
      timeout: 10s
      retries: 10


  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    # Keep MQTT port exposed for external MQTT clients
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - rfid-net
    environment:
      DB_HOST: database
      DB_USER: rfid
      DB_PASSWORD: rfidpass
      DB_NAME: rfid_db
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 mosquitto_sub -t '$$SYS/#' -C 1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt-subscriber:
    build: ./mqtt-python-server
    container_name: mqtt_client
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      mqtt-broker:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: rfid
      DB_PASSWORD: rfidpass
      DB_NAME: rfid_db
      MQTT_BROKER: mosquitto
      DB_PORT: "3306"
      MQTT_PORT: "1883"
      PYTHONUNBUFFERED: 1
      DOCKER_ENV: "1"
    networks:
      - rfid-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 20s
      timeout: 10s
      retries: 10
    expose:
      - "8080"  # Health check port
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: nest_api
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"  # Expose API port for external access
    environment:
      DB_HOST: database
      DB_USER: rfid
      DB_PASSWORD: rfidpass
      DB_NAME: rfid_db
      PORT: 5000
      DB_PORT: 3306
      NODE_ENV: production
    networks:
      - rfid-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build: ./frontend
    container_name: nextjs_app
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    # Remove port mapping as it's only needed internally
    ports:
      - "3000:3000"  # Expose Next.js app port for external access
    environment:
      PORT: 3000
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000
    networks:
      - rfid-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mysql_data:
  mosquitto_data:
  mosquitto_log:

networks:
  rfid-net:
    driver: bridge
