#!/bin/bash

echo "🧪 RFID Cards API Test Suite"
echo "============================"
echo ""
echo "Available test commands:"
echo ""
echo "📋 Individual Tests:"
echo "  npm run test:rfid-cards           - Run service unit tests"
echo "  npm run test:rfid-cards:controller - Run controller unit tests" 
echo "  npm run test:rfid-cards:e2e       - Run end-to-end tests (requires DB)"
echo ""
echo "🚀 Combined Tests:"
echo "  npm run test:rfid-cards:all       - Run all unit tests (service + controller)"
echo ""
echo "🔄 Development:"
echo "  npm run test:rfid-cards:watch     - Watch mode for continuous testing"
echo "  npm run test:rfid-cards:coverage  - Generate coverage report"
echo ""
echo "🔧 Standard Commands:"
echo "  npm test                          - Run all tests"
echo "  npm run test:watch                - Watch all tests"
echo "  npm run test:cov                  - Coverage for all tests"
echo "  npm run test:e2e                  - All e2e tests"
echo ""
echo "💡 Quick Start:"
echo "  Run 'npm run test:rfid-cards:all' to test all RFID functionality"
echo ""
